version: "3.3"
services:

  php:
    build: .
    ports: 
      - 8000:80
    volumes:
      - ./src:/var/www/html
    links:
      - db
    networks:
      - default

  db:
    image: mysql
    ports: 
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db:db
    ports:
      - 8080:80
    environment:
      MYSQL_USER: default
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password